bookmarker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # moved here because of the namespacing in the accounts

    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='auth/password_reset_form.html'),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='auth/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='auth/password_reset_confirm.html'),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('social-auth/',include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views
app_name = 'images'

urlpatterns = [
    path('<int:id>/<slug:slug>', views.image_detail, name='detail'),
    path('create/', views.image_create, name='create'),
    path('like/', views.image_like, name='like'),
    # path('comment/', views.image_comment, name='comment'),
    path('', views.image_list, name='list'),
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import  slugify
from django.urls import reverse
# Create your models here.
class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='images_created',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,db_index=True)
    users_like=models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked',blank=True)
    
    def __str__(self):
        return self.title

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Image'
        verbose_name_plural = 'Images'
    # override save to generate a slug for each image
    def save(self, *args, **kwargs):
       if not self.slug:
           self.slug=slugify(self.title)
       super().save(*args, **kwargs) # Call the real save() method

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id,self.slug])

# class Comment(models.Model):
#     image=models.ForeignKey(Image,related_name='image_comment',on_delete=models.CASCADE)
#     created=models.DateField(auto_now_add=True,db_index=True)
#     user=models.ForeignKey(settings.AUTH_USER_MODEL,related_name='user_comment',on_delete=models.CASCADE)
#     body=models.TextField(blank=True)
#     def __str__(self):
#         pass

#     class Meta:
#         db_table = ''
#         managed = True
#         verbose_name = 'Comment'
#         verbose_name_plural = 'Comments'

images/forms.py
from django import  forms
from django.core.exceptions import ValidationError
from django.forms import widgets
from .models import Image

from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageCreateForm(forms.ModelForm):
    
    class Meta:
        model = Image
        fields = ("title","url","description")
        widgets={
            'url':forms.HiddenInput(attrs={'hidden':"hidden"}),
            'title':forms.TextInput(attrs={'class':"form-control",'required':'required'}),
            'description':forms.Textarea(attrs={'class':"form-control",'rows':"3"}),
             
                                            
        }
    def clean_url(self):
        url=self.cleaned_data['url']
        valid_ext=['jpg','jpeg','png']
        ext=url.rsplit('.',1)[1].lower()
        if ext not in valid_ext:
            raise ValidationError('The given url does not cntin allowed extension')
        return url

    def save(self,force_insert=False,force_update=False,commit=True):
        image=super().save(commit=False)
        image_url=self.cleaned_data['url']
        name=slugify(image.title)
        extension=image.url.rsplit('.',1)[1].lower()
        image_name=f'{name}.{extension}'
    

        # fetch image from url
        res=request.urlopen(image_url)
        image.image.save(image_name,ContentFile(res.read()),save=False)

        if commit:
            image.save()
        return image

# class CommentForm(forms.ModelForm):
    
#     class Meta:
#         model = Comment
#         fields = ('body',)
#         widgets={
#             'body':forms.TextInput(attrs={'class':"form-control",'required':'required'}),
#         }
        

images/views.py
from django.core import paginator
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib import messages
from .forms import ImageCreateForm
from .models import Image
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from bookmarker.common.decorators import ajax_required

# Create your views here.


@login_required
def image_create(request):

    if request.method=='POST':
        form=ImageCreateForm(request.POST)
        if form.is_valid():
            cd =form.cleaned_data
            new_item=form.save(commit=False)

            new_item.user=request.user
            new_item.save()
            messages.success(request,'Image added successfully')
            return redirect(new_item.get_absolute_url())
    else:
        form=ImageCreateForm(data=request.GET)


    return render(request,'images/create.html',{'section':'images','form':form})

def image_detail(request,id,slug):
    image=get_object_or_404(Image,id=id,slug=slug)
    return render(request,"images/detail.html",{'image':image})

@login_required
@require_POST
def image_like(request):
    image_id=request.POST.get('id')
    action=request.POST.get('action')
    try:
        image=Image.objects.get(id=image_id)
        if action=="like":
            image.users_like.add(request.user)
        else:
            image.users_like.remove(request.user)
        return JsonResponse({'status':'ok'})
    except:
        pass
    return JsonResponse({'status':'error'})

# @login_required
# @require_POST
# def image_comment(request):
    
#     if request.method=='POST':
#         form=CommentForm(request.POST)
#         if form.is_valid():
#             cd =form.cleaned_data
#             new_item=form.save(commit=False)
#             new_item.user=request.user
#             im=Image.get_object_or_404(id=request.POST.get('id'))
#             new_item.image=im
#             new_item.save()
#             # messages.success(request,'Image added successfully')
#             return redirect(im.get_absolute_url())
#     else:
#         form=CommentForm()
#     return JsonResponse({'status':'error'})


def image_list(request):
    images=Image.objects.all()
    paginator=Paginator(images,8)
    page=request.GET.get('page')
    try:
        images=paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                      'images/image/list_ajax.html',
                      {'section': 'images', 'images': images})
    return render(request,
                  'images/list.html',
                   {'section': 'images', 'images': images})

images/templates/images/comment.html
 <div class="new-comment">
                                                    <form method=" {% url 'images:comment' %} ">
                                                        <div class="input-group">
                                                        {% csrf_token %}
                                                            {{comment}}
                                                            <div class="input-group-append">
                                                                <button class="btn btn-secondary" type="button" id="button-addon1">Comment</button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>

images/templates/images/create.html
{% extends 'dash/dashbase.html' %}
{% block maincontent %}

<div class="page-inner no-page-title">
                    <div id="main-wrapper">
                        <div class="content-header">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb breadcrumb-style-1">
                                    <li class="breadcrumb-item"><a href="#">Forms</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Form Elements</li>
                                </ol>
                            </nav>
                            <h1 class="page-title">Edit Profile</h1>
                        </div>
                        
                        {% if resp %}
                        <div class="alert alert-success" role="alert">
                                {{resp}}
                        </div>
                        {% endif %}

                        <div class="row">
                            <div class="col-md-6">

                                <div class="card ">

                                    

                                    <div class="card-body">
                                        <div class="embed-responsive embed-responsive-1by1">
                                            <img alt="Card image cap" class="card-img-top embed-responsive-item" src="{{ request.GET.url }}" />
                                         </div>                                        
                                         
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title">Create Image Bookmark</h5>
                                          
                                        <form method="POST" class="needs-validation" novalidate>
                                        {% csrf_token %}
                                            {% for field in form %}
                                            <div class="form-group">
                                                <label for="field.name">{{field.name}}</label>
                                                {{field}}
                                                {% comment %} <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> {% endcomment %}
                                            </div>
                                            {% endfor %}
                                              
                                            
                                        
    

                                            
                                           
                                            <button class="btn btn-primary" type="submit">Bookmark It</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                       
</div>


{% endblock  %}

images/templates/images/detail.html
{% extends 'dash/dashbase.html' %}
{% load static %}


{% block maincontent %}

 <!-- Page Inner -->
                <div class="page-inner no-page-title contacts-app">
                    <div id="main-wrapper">
                        
                        <div class="row">
                            <div class="col-xl-3">
                                
                            </div>
                            <div class="col-xl-6">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="post">
                                            
                                        {% with total_likes=image.users_like.count users_like=image.users_like.all %}
                                            <div class="post-header">
                                                <img src="../../assets/images/avatars/avatar4.png">
                                                <div class="post-info">
                                                    <span class="post-author">{{image.title}}</span><br>
                                                    <span class="post-date">3hrs</span>
                                                </div>
                                                <div class="post-header-actions">
                                                    <a href="#"><i class="fas fa-ellipsis-h"></i></a>
                                                </div>
                                            </div>
                                            <div class="post-body">
                                                <p>{{image.description}}.</p>
                                                <div class="post-actions">
                                                <ul class="list-unstyled">
                                                    <li>
                                                    <a ><i class="far fa-heart"> <span class="total"> 
                                                    {{ total_likes }}
                                                    </span> like{{ total_likes|pluralize }}</i></a>
                                                        
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="far fa-comment"></i>5 Comment</a>
                                                    </li>
                                                   
                                                </ul>
                                            </div>
                                                <img src="{{image.image.url}}" class="post-image" alt="">
                                               
                                            </div>
                                            <div class="post-actions">
                                                <ul class="list-unstyled">
                                                    <li>
                                                        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
                                                            {% if request.user not in users_like %}
                                                                <i class="far fa-heart"></i>Like
                                                            {% else %}
                                                            <i class="fas fa-heart"></i> Unlike
                                                            {% endif %}
                                                        </a>
                                                        
                                                        
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="far fa-comment"></i>Comment</a>
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="fas fa-share"></i>Share</a>
                                                    </li>
                                                </ul>

                                                
                                            </div>
                                            <div class="post-comments">
                                                <div class="post-comm">
                                                    <img src="../../assets/images/avatars/avatar2.png" class="comment-img">
                                                    <div class="comment-container">
                                                        <span class="comment-author">
                                                            Sonny Rosas
                                                            <small class="comment-date">5min</small>
                                                        </span>
                                                    </div>
                                                    <span class="comment-text">
                                                        Mauris ultrices convallis massa, nec facilisis enim interdum ac.
                                                    </span>
                                                </div>
                                                <div class="post-comm">
                                                    <img src="../../assets/images/avatars/avatar1.png" class="comment-img">
                                                    <div class="comment-container">
                                                        <span class="comment-author">
                                                            Jacob Lee
                                                            <small class="comment-date">27min</small>
                                                        </span>
                                                    </div>
                                                    <span class="comment-text">
                                                        Cras tincidunt quam nisl, vitae aliquet enim pharetra at. Nunc varius bibendum turpis, vitae ultrices tortor facilisis ac.
                                                    </span>
                                                </div>
                                                <div class="new-comment">
                                                    <form action="javascript: void(0)">
                                                        <div class="input-group">
                                                            <input type="text" name="comment" class="form-control search-input" placeholder="Type something...">
                                                            <div class="input-group-append">
                                                                <button class="btn btn-secondary" type="button" id="button-addon1">Comment</button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        {% endwith %}
                                            
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                            <div class="col-xl-3">
                                
                            </div>
                        </div>
                        
                    </div><!-- Main Wrapper -->

                    
                   
                </div><!-- /Page Inner -->
{% endblock  %}


{% block domready %}
    $('a.like').click(function(e){
        e.preventDefault(); 
            $.post('{% url "images:like" %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
        function(data){
            if (data['status'] == 'ok')
            {
            var previous_action = $('a.like').data('action');
            // toggle data-action
            $('a.like').data('action', previous_action == 'like' ?
            'unlike' : 'like');
            // toggle link text
            $('a.like').text(previous_action == 'like' ? 'Unlike' :
            'Like');
            // update total likes
            var previous_likes = parseInt($('span.total').
            text());
            $('span.total').text(previous_action == 'like' ?
            previous_likes + 1 : previous_likes - 1);
            }
        }
        );
  });

{% endblock %}

images/templates/images/list_ajax.html
{% extends 'dash/dashbase.html' %}
{% load static %}


{% block maincontent %}

 <!-- Page Inner -->
                <div class="page-inner no-page-title contacts-app">
                    <div id="main-wrapper">
                        
                        <div class="row">
                            <div class="col-xl-3">
                                
                            </div>
                            {% for im in images %}
                            
                            <div class="col-xl-6">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="post">
                                            
                                        {% with total_likes=image.users_like.count users_like=image.users_like.all %}
                                            <div class="post-header">
                                                <img src="../../assets/images/avatars/avatar4.png">
                                                <div class="post-info">
                                                    <span class="post-author">{{image.title}}</span><br>
                                                    <span class="post-date">{{image.created}} by <b>{{image.user}}</b></span>
                                                </div>
                                                <div class="post-header-actions">
                                                    <a href="#"><i class="fas fa-ellipsis-h"></i></a>
                                                </div>
                                            </div>
                                            <div class="post-body">
                                                <p>{{image.description}}.</p>
                                                <div class="post-actions">
                                                <ul class="list-unstyled">
                                                    <li>
                                                    <a ><i class="far fa-heart"> <span class="total"> 
                                                    {{ total_likes }}
                                                    </span> like{{ total_likes|pluralize }}</i></a>
                                                        
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="far fa-comment"></i>5 Comment</a>
                                                    </li>
                                                   
                                                </ul>
                                            </div>
                                                <img src="{{image.image.url}}" class="post-image" alt="">
                                               
                                            </div>
                                            <div class="post-actions">
                                                <ul class="list-unstyled">
                                                    <li>
                                                        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
                                                            {% if request.user not in users_like %}
                                                                <i class="far fa-heart"></i>Like
                                                            {% else %}
                                                            <i class="fas fa-heart"></i> Unlike
                                                            {% endif %}
                                                        </a>
                                                        
                                                        
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="far fa-comment"></i>Comment</a>
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="fas fa-share"></i>Share</a>
                                                    </li>
                                                </ul>

                                                
                                            </div>
                                            <div class="post-comments">
                                                <div class="post-comm">
                                                    <img src="../../assets/images/avatars/avatar2.png" class="comment-img">
                                                    <div class="comment-container">
                                                        <span class="comment-author">
                                                            Sonny Rosas
                                                            <small class="comment-date">5min</small>
                                                        </span>
                                                    </div>
                                                    <span class="comment-text">
                                                        Mauris ultrices convallis massa, nec facilisis enim interdum ac.
                                                    </span>
                                                </div>
                                                <div class="post-comm">
                                                    <img src="../../assets/images/avatars/avatar1.png" class="comment-img">
                                                    <div class="comment-container">
                                                        <span class="comment-author">
                                                            Jacob Lee
                                                            <small class="comment-date">27min</small>
                                                        </span>
                                                    </div>
                                                    <span class="comment-text">
                                                        Cras tincidunt quam nisl, vitae aliquet enim pharetra at. Nunc varius bibendum turpis, vitae ultrices tortor facilisis ac.
                                                    </span>
                                                </div>
                                                <div class="new-comment">
                                                    <form id="commentform" action="">
                                                        <div class="input-group">
                                                        {% csrf_token %}
                                                                <input type="text" hidden=hidden name="id" value="{{image.id}}">
                                                                <input type="text" name="body" class="form-control search-input" placeholder="Type something...">
                                                                <div class="input-group-append">
                                                                    <button class="btn btn-secondary" type="button" id="submitBtn">Comment</button>
                                                                </div>
                                                            
                                                            
                                                        </div>
                                                    </form>
                                                </div> 
                                            </div>
                                        {% endwith %}
                                            
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                            
                            {% endfor %}
                            <div class="col-xl-3">
                                
                            </div>
                        </div>
                        
                    </div><!-- Main Wrapper -->

                    
                   
                </div><!-- /Page Inner -->
{% endblock  %}


{% block domready %}
    $('a.like').click(function(e){
        e.preventDefault(); 
            $.post('{% url "images:like" %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
        function(data){
            if (data['status'] == 'ok')
            {
            var previous_action = $('a.like').data('action');
            // toggle data-action
            $('a.like').data('action', previous_action == 'like' ?
            'unlike' : 'like');
            // toggle link text
            $('a.like').text(previous_action == 'like' ? 'Unlike' :
            'Like');
            // update total likes
            var previous_likes = parseInt($('span.total').
            text());
            $('span.total').text(previous_action == 'like' ?
            previous_likes + 1 : previous_likes - 1);
            }
        }
        );
  });

{% endblock %}